name: "AnthonyCastronova.com"
description: ""
url: "http://localhost:4000/"
permalink: pretty
highlighter: true
markdown: kramdown

paginate: 3
paginate_path: "/blog/page:num"


gems: [jekyll-paginate, jekyll-sitemap]
