name: "AnthonyCastronova.com"
description: ""
url: "http://www.anthonycastronova.com"
permalink: pretty
highlighter: true
markdown: kramdown

paginate: 3
paginate_path: "/blog/page:num"


sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"


gems: [jekyll-paginate]
