name: "AnthonyCastronova.com"
description: ""
url: "http://localhost:4000/"
permalink: pretty
pygments: true
markdown: kramdown

paginate: 3
paginate_path: "/blog/page:num"


gems: [jekyll-sitemap]
# gems: [jekyll-sitemap]
  # - jekyll-last-modified-at
